#\.grakn console --keyspace zeitlabs ../zeitlabs/schema_zeitlabs3.gql

define

    # entities
    topic sub entity,
        has title,
        has txt,
        plays level0;

    subtopic1 sub entity,
        has title,
        has txt,
        plays level1;
    

    subtopic2 sub entity,
        has title,
        has txt,
        plays level2;
    

    subtopic3 sub entity,
        has title,
        has txt,
        plays level3;



    # relations

    rel1 sub relation,
        has title,
        relates level0,
        relates level1;

    rel2 sub relation,
        has title,
        relates level1,
        relates level2;

    rel3 sub relation,
        has title,
        relates level2,
        relates level3;


    # attributes

    title sub attribute, 
        value string;

    txt sub attribute, 
        value string;

