version: "2.0"
nlu:
- intent: bot_challenge
  examples: |
    - Are you a bot?
- intent: stop
  examples: |
    - shut up
- intent: query
  examples: |
    - Can I ask you a question?
    - I have a question
- intent: subscribe
  examples: |
    - I want to get the newsletter
    - Can you sign me up for the newsletter?
- intent: thankyou
  examples: |
    - thank you very much
    - no thank you
- intent: inform
  examples: |
    - Email is something@example.com
    - Please send it to anything@example.com
    - random@example.com
- intent: greet
  examples: |
    - Hi
    - Good morning
    - Hallo
    - Good day
- intent: next_level_deny
  examples: |
    - not interested
    - no
    - I dont want to
    - get out
    - nope
- intent: reset
  examples: |
    - please start over
    - lets choose a new topic
    - reset
    - go back
    - restart
- intent: bye
  examples: |
    - i am done
    - see you later
    - thats all
    - ttyl
    - ok bye
    - will talk later
- intent: next_level_affirm
  examples: |
    - yes please
    - yes I would like to know more
    - why not
    - absolutely
    - continue
    - please continue
    - certainly
    - go on
    - Ok sure
- intent: reset_topic
  examples: |
    - do you know any other topics execept this one?
    - new topic please?
    - lets look at something else
    - can we discuss something else
    - can I please change the subject
    - what other topics do you know?
    - I am not interested in [data science](Tparent)
    - change the topic
    - something else
    - not interesting
- intent: know_about
  examples: |
    - Can you explain [Artificial Intelligence](Tparent) to me?
    - [Reinforcement Learning](Tparent)
    - I would want to learn about [Python](Tparent).
    - I don`t know a lot about [Data Science](Tparent)
    - [Data Science](Tparent)
    - Lets explore [Artificial Intelligence](Tparent)
    - I would want to learn about [Artificial Intelligence](Tparent).
    - What is [Data Science](Tparent)?
    - Describe [Reinforcement Learning](Tparent)?
    - Can you explain [Data Science](Tparent) to me?
    - Define [Data Science](Tparent)?
    - Lets talk about [Python](Tparent)
    - [Python](Tparent)
    - I don`t know a lot about [Machine Learning](Tparent)
    - What is [Artificial Intelligence](Tparent)?
    - Lets explore [Reinforcement Learning](Tparent)
    - Perhaps [Reinforcement Learning](Tparent)
    - What is [Machine Learning](Tparent)?
    - Can you tell me about [Python](Tparent)?
    - Can you tell me about [Reinforcement Learning](Tparent)?
    - Define [Python](Tparent)?
    - How about [Reinforcement Learning](Tparent)?
    - Lets explore [Data Science](Tparent)
    - Tell me about [Python](Tparent)?
    - What do you know about [Python](Tparent)?
    - What do you know about [Data Science](Tparent)?
    - Perhaps [Artificial Intelligence](Tparent)
    - Perhaps [Python](Tparent)
    - How about [Machine Learning](Tparent)?
    - Tell me about [Reinforcement Learning](Tparent)?
    - How about [Artificial Intelligence](Tparent)?
    - I don`t know a lot about [Reinforcement Learning](Tparent)
    - Lets talk about [Artificial Intelligence](Tparent)
    - Can you tell me about [Artificial Intelligence](Tparent)?
    - Tell me about [Machine Learning](Tparent)?
    - Can you explain [Machine Learning](Tparent) to me?
    - What do you know about [Reinforcement Learning](Tparent)?
    - I don`t know a lot about [Artificial Intelligence](Tparent)
    - Can you tell me about [Data Science](Tparent)?
    - Perhaps [Data Science](Tparent)
    - Can you tell me about [Machine Learning](Tparent)?
    - Lets explore [Machine Learning](Tparent)
    - What do you know about [Artificial Intelligence](Tparent)?
    - Lets talk about [Reinforcement Learning](Tparent)
    - Describe [Python](Tparent)?
    - Lets talk about [Data Science](Tparent)
    - Please explain [Artificial Intelligence](Tparent)
    - I would want to learn about [Reinforcement Learning](Tparent).
    - Please explain [Reinforcement Learning](Tparent)
    - How about [Python](Tparent)?
    - Perhaps [Machine Learning](Tparent)
    - Define [Reinforcement Learning](Tparent)?
    - Lets explore [Python](Tparent)
    - What do you know about [Machine Learning](Tparent)?
    - Please explain [Machine Learning](Tparent)
    - [Artificial Intelligence](Tparent)
    - Tell me about [Artificial Intelligence](Tparent)?
    - What is [Reinforcement Learning](Tparent)?
    - How about [Data Science](Tparent)?
- intent: next_level
  examples: |
    - \tDescribe [Applications](Tchild)?
    - \tHow about [See also](Tchild)?
    - \tTell me about [References](Tchild)?
    - \tI would want to learn about [General issues](Tchild).
    - \tCan you explain [introduction](Tchild) to me?
    - \tCan you tell me about [See also](Tchild)?
    - \tLets talk about [Generalizations](Tchild)
    - \tI don’t know a lot about [Generative training](Tchild)
    - \tDefine [Steps](Tchild)?
    - \tHow about [Generalizations](Tchild)?
    - \tDefine [Algorithm choice](Tchild)?
    - \tCan you tell me about [How supervised learning algorithms work](Tchild)?
    - \tPerhaps [Applications](Tchild)
    - \tPerhaps [See also](Tchild)
    - \t[Generalizations](Tchild)
    - \tI don’t know a lot about [Generalizations](Tchild)
    - \t[Algorithm choice](Tchild)
    - \t[References](Tchild)
    - \tCan you tell me about [References](Tchild)?
    - \tDefine [See also](Tchild)?
    - \tTell me about [Generalizations](Tchild)?
    - \tDescribe [Approaches and algorithms](Tchild)?
    - \tPerhaps [External links](Tchild)
    - \tLets talk about [introduction](Tchild)
    - \tWhat do you know about [References](Tchild)?
    - \tCan you explain [How supervised learning algorithms work](Tchild) to me?
    - \tWhat do you know about [Approaches and algorithms](Tchild)?
    - \tHow about [introduction](Tchild)?
    - \tCan you tell me about [External links](Tchild)?
    - \tWhat do you know about [General issues](Tchild)?
    - \tTell me about [Generative training](Tchild)?
    - \tHow about [Applications](Tchild)?
    - \tLets explore [Steps](Tchild)
    - \tCan you explain [External links](Tchild) to me?
    - \tLets talk about [Applications](Tchild)
    - \tCan you explain [Approaches and algorithms](Tchild) to me?
    - \tPerhaps [General issues](Tchild)
    - \tLets explore [Applications](Tchild)
    - \tLets talk about [External links](Tchild)
    - \tDefine [References](Tchild)?
    - \tPerhaps [Approaches and algorithms](Tchild)
    - \tTell me about [Algorithm choice](Tchild)?
    - \tWhat is [See also](Tchild)?
    - \tLets talk about [Approaches and algorithms](Tchild)
    - \tDescribe [How supervised learning algorithms work](Tchild)?
    - \tDefine [Generative training](Tchild)?
    - \tHow about [Steps](Tchild)?
    - \tLets talk about [How supervised learning algorithms work](Tchild)
    - \tPlease explain [Generalizations](Tchild)
    - \tWhat is [Approaches and algorithms](Tchild)?
    - \tWhat is [Generalizations](Tchild)?
    - \tWhat do you know about [How supervised learning algorithms work](Tchild)?
    - \tLets explore [General issues](Tchild)
    - \tI would want to learn about [Approaches and algorithms](Tchild).
    - \tI don’t know a lot about [Steps](Tchild)
    - \tDescribe [References](Tchild)?
    - \tCan you tell me about [Steps](Tchild)?
    - \tI would want to learn about [Algorithm choice](Tchild).
    - \tDescribe [General issues](Tchild)?
    - \tDescribe [Generalizations](Tchild)?
    - \tWhat is [How supervised learning algorithms work](Tchild)?
    - \tTell me about [See also](Tchild)?
    - \tTell me about [How supervised learning algorithms work](Tchild)?
    - \tTell me about [Applications](Tchild)?
    - \tCan you explain [Generative training](Tchild) to me?
    - \tHow about [Algorithm choice](Tchild)?
    - \tWhat is [introduction](Tchild)?
    - \tDefine [Applications](Tchild)?
    - \tHow about [Generative training](Tchild)?
    - \tI would want to learn about [Generative training](Tchild).
    - \tWhat do you know about [External links](Tchild)?
    - \tI would want to learn about [Steps](Tchild).
    - \t[Generative training](Tchild)
    - \tCan you tell me about [Algorithm choice](Tchild)?
    - \tPlease explain [See also](Tchild)
    - \tDefine [Approaches and algorithms](Tchild)?
    - \tLets explore [Generative training](Tchild)
    - \tHow about [General issues](Tchild)?
    - \tLets talk about [See also](Tchild)
    - \tCan you tell me about [Generalizations](Tchild)?
    - \tLets explore [Approaches and algorithms](Tchild)
    - \tLets explore [Generalizations](Tchild)
    - \tDefine [How supervised learning algorithms work](Tchild)?
    - \tPlease explain [General issues](Tchild)
    - \tPlease explain [Applications](Tchild)
    - \tCan you explain [Steps](Tchild) to me?
    - \tI would want to learn about [Applications](Tchild).
    - \tTell me about [General issues](Tchild)?
    - \tCan you tell me about [General issues](Tchild)?
    - \tHow about [Approaches and algorithms](Tchild)?
    - \tLets explore [How supervised learning algorithms work](Tchild)
    - \tI don’t know a lot about [introduction](Tchild)
    - \t[See also](Tchild)
    - \tDescribe [introduction](Tchild)?
    - \tHow about [References](Tchild)?
    - \tWhat is [Steps](Tchild)?
    - \t[General issues](Tchild)
    - \tPerhaps [Generative training](Tchild)
    - \tI don’t know a lot about [External links](Tchild)
    - \tDescribe [Generative training](Tchild)?
    - \tCan you tell me about [Approaches and algorithms](Tchild)?
    - \tCan you tell me about [introduction](Tchild)?
    - \tWhat do you know about [Generative training](Tchild)?
    - \t[External links](Tchild)
    - \tPerhaps [introduction](Tchild)
    - \t[introduction](Tchild)
    - \tLets talk about [Steps](Tchild)
    - \tPerhaps [How supervised learning algorithms work](Tchild)
    - \tI don’t know a lot about [References](Tchild)
    - \tLets explore [Algorithm choice](Tchild)
    - \tDescribe [Steps](Tchild)?
    - \tI would want to learn about [How supervised learning algorithms work](Tchild).
    - \tCan you explain [Applications](Tchild) to me?
    - \tCan you explain [Generalizations](Tchild) to me?
    - \tI would want to learn about [Generalizations](Tchild).
    - \tLets explore [External links](Tchild)
    - \tI would want to learn about [External links](Tchild).
    - \tCan you tell me about [Applications](Tchild)?
    - \tPlease explain [Generative training](Tchild)
    - \tPlease explain [Approaches and algorithms](Tchild)
    - \tWhat do you know about [See also](Tchild)?
    - \tDescribe [External links](Tchild)?
    - \tTell me about [Approaches and algorithms](Tchild)?
    - \tI would want to learn about [See also](Tchild).
    - \tPlease explain [introduction](Tchild)
    - \tI don’t know a lot about [How supervised learning algorithms work](Tchild)
    - \t[Steps](Tchild)
    - \tWhat do you know about [Algorithm choice](Tchild)?
    - \tWhat is [Applications](Tchild)?
    - \t[How supervised learning algorithms work](Tchild)
    - \tLets talk about [Algorithm choice](Tchild)
    - \tWhat do you know about [Applications](Tchild)?
    - \t[Approaches and algorithms](Tchild)
    - \tPlease explain [References](Tchild)
    - \tI don’t know a lot about [General issues](Tchild)
    - \tWhat is [Generative training](Tchild)?
    - \tPerhaps [Algorithm choice](Tchild)
    - \tLets explore [See also](Tchild)
    - \tHow about [How supervised learning algorithms work](Tchild)?
    - \tCan you explain [Algorithm choice](Tchild) to me?
    - \tPlease explain [How supervised learning algorithms work](Tchild)
    - \tCan you explain [See also](Tchild) to me?
    - \tWhat do you know about [Steps](Tchild)?
    - \tPerhaps [Generalizations](Tchild)
- lookup: Tparent
  examples: |
    - Machine Learning
    - Python (programming language)
    - Data Science
    - Reinforcement Learning
    - Artificial Intelligence
- lookup: Tchild
  examples: |
    - Overview
    - History and relationships to other fields
    - Theory
